=== haibocheng/des/daemon/conf/conf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element name="scheduler">
    				<xs:complexType>
    					<xs:sequence>
    						<xs:element name="max-workers" type="xs:integer" />
    					</xs:sequence>
    				</xs:complexType>
    			</xs:element>
    			<xs:element name="queue">
    				<xs:complexType>
    					<xs:sequence>
    						<xs:element name="adapter" type="xs:string" />
    						<xs:element name="dsn" type="xs:anyURI" />
    						<xs:element name="queue" type="xs:string" />
    					</xs:sequence>
    				</xs:complexType>
    			</xs:element>
    			<xs:element name="data">
    				<xs:complexType>
    					<xs:sequence>
    						<xs:element name="driver" type="xs:string" />
    						<xs:element name="dsn" type="xs:anyURI" />
    					</xs:sequence>
    				</xs:complexType>
    			</xs:element>
    			<xs:element name="profiles" type="xs:anyURI" />
    			<xs:element name="commands">
    				<xs:complexType>
    					<xs:sequence>
    						<xs:element minOccurs="1" maxOccurs="unbounded" ref="command" />
    					</xs:sequence>
    				</xs:complexType>
    			</xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
	<xs:element name="command">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" />
				<xs:element name="path" type="xs:anyURI" />
				<xs:element name="options-type" type="xs:string" />
				<xs:element name="template" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== haibocheng/des/daemon/conf/server-node-windows.xml
<?xml version="1.0" encoding="UTF-8"?>
<config
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="conf.xsd">
	<!-- Threads -->
	<threads>
		<max-threads>8</max-threads>
	</threads>
	
	<!-- Queue -->
	<queue>
		<adapter>activemq</adapter>
		<dsn>tcp://localhost:61616</dsn>
		<queue>des-msgs</queue>
	</queue>
	
	<!-- Data -->
	<data>
		<driver>com.mysql.jdbc.Driver</driver>
		<dsn>jdbc:mysql://des:des123@localhost:3306/des</dsn>
	</data>
	
	<!-- Paths -->
	<profiles>profiles</profiles>
	
	<!-- Commands -->
	<commands>
		<!-- FFmpeg -->
		<command>
			<name>FFMpeg</name>
			<path>commands/ffmpeg-git-01a73d6-win64-shared/bin/ffmpeg.exe</path>
			<options-type>POSIX</options-type>
			<template>%1$2s -i %2$2s%3$2s %4$2s</template>
		</command>
		
		<!-- Image Magick -->
		<command>
			<name>IMagick</name>
			<path>commands/ImageMagick-6.7.0-Q16/convert.exe</path>
			<options-type>POSIX</options-type>
			<template>%1$2s %2$2s%3$2s %4$2s</template>
		</command>
		
		<!-- F4F Packager -->
		<command>
			<name>F4FPackager</name>
			<path>commands/File_Packager_1.0_Windows_x64/adobe/f4fpackager/f4fpackager.exe</path>
			<options-type>GNU</options-type>
			<template>%1$2s --input-file=%2$2s%3$2s --output-path=%4$2s</template>
		</command>
		
		<!-- MP4 Box -->
		<command>
			<name>MP4Box</name>
			<path>commands/mp4box-0.4.6-rev2735/MP4Box.exe</path>
			<options-type>POSIX</options-type>
			<template>%1$2s %3$2s %2$2s</template>
		</command>
	</commands>
	
</config>

=== haibocheng/des/daemon/conf/server-node.xml
<?xml version="1.0" encoding="UTF-8"?>
<config
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="conf.xsd">
	
	<!-- Threads -->
	<scheduler>
		<max-workers>8</max-workers>
	</scheduler>
	
	<!-- Queue -->
	<queue>
		<adapter>activemq</adapter>
		<dsn>tcp://localhost:61616</dsn>
		<queue>des-msgs</queue>
	</queue>
	
	<!-- Data -->
	<data>
		<driver>com.mysql.jdbc.Driver</driver>
		<dsn>jdbc:mysql://des:des123@localhost:3306/des</dsn>
	</data>
	
	<!-- Paths -->
	<profiles>profiles</profiles>
	
	<!-- Commands -->
	<commands>
		<!-- FFmpeg -->
		<command>
			<name>FFMpeg</name>
			<path>/tools/ffmpeg-20120416-git-4fa706a-win64-static/bin/ffmpeg.exe</path>
			<options-type>POSIX</options-type>
			<template>%1$2s -i %2$2s%3$2s %4$2s</template>
		</command>
		
		<!-- Image Magick -->
		<command>
			<name>IMagick</name>
			<path>/tools/ImageMagick-6.7.6-Q16/convert.exe</path>
			<options-type>POSIX</options-type>
			<template>%1$2s %2$2s%3$2s %4$2s</template>
		</command>
		
		<!-- F4F Packager -->
		<command>
			<name>F4FPackager</name>
			<path>/tools/adobe_f4fpackager_4_5_1_windows_x64/f4fpackager.exe</path>
			<options-type>GNU</options-type>
			<template>%1$2s --input-file=%2$2s%3$2s --output-path=%4$2s</template>
		</command>
		
		<!-- MP4 Box -->
		<command>
			<name>MP4Box</name>
			<path>/tools/MP4Box-0.4.6-rev2735/MP4Box.exe</path>
			<options-type>POSIX</options-type>
			<template>%1$2s %3$2s %2$2s</template>
		</command>
	</commands>
	
</config>
