=== haibocheng/des/daemon/schemes/dmes.dtd
<!--The DES Message Format-->
<!ELEMENT dmes (message+|report?)+>
<!ATTLIST dmes
	id		ID		#REQUIRED>
<!ELEMENT message (file?|options*|command?|post-process*)*>
<!ATTLIST message
	id		ID		#IMPLIED
	pid		IDREFS	#IMPLIED
	extends CDATA	#IMPLIED>
<!ELEMENT file	EMPTY>
<!ATTLIST file
	input	CDATA	#IMPLIED
	output	CDATA	#IMPLIED>
<!ELEMENT options (option*)?>
<!ELEMENT option	(#PCDATA)>
<!ATTLIST option
	name	CDATA	#REQUIRED>
<!ELEMENT command	(#PCDATA)>
<!ELEMENT post-process (options*|command?)*>

<!ELEMENT report (writer+|report-messages)+>
<!ELEMENT writer (mapping)>
<!ATTLIST writer
	type	(sql|hashtable|text) #REQUIRED>
<!ELEMENT mapping (field)+>
<!ELEMENT field (#PCDATA)>
<!ATTLIST field
	key		(id|state|messages) #REQUIRED>
<!ELEMENT report-messages (report-message+)>
<!ELEMENT report-message (#PCDATA)>
<!ATTLIST report-message
	key		(CORRUPT_FILE|GENERAL_ERROR)	#REQUIRED>

=== haibocheng/des/daemon/profiles/mp4-hq.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dmes SYSTEM "../schemes/dmes.dtd">
<dmes>
	<options>
		<option name="s">hd720</option>
		<option name="b">2M</option>
		<option name="bt">4M</option>
		<option name="vcodec">libx264</option>
		<option name="threads">4</option>
		<option name="ar">48000</option>
		<option name="ab">192k</option>
	</options>
	
	<command>FFMpeg</command>
	
	<post-process>
		<tool>MP4Box</tool>
		<options>
			<option name="hint"></option>
			<option name="mpeg4"></option>
			<option name="inter">500</option>
		</options>
	</post-process>
</dmes>
